Compile error
I had trouble compiling ex_cldr with the following error:

```
== Compilation error in file lib/cldr/language_tag.ex ==
** (ArgumentError) Jason.Encoder is not available, cannot derive Jason.Encoder for Cldr.LanguageTag
    (elixir) lib/protocol.ex:69: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:715: Protocol.derive/5
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) lib/protocol.ex:708: Protocol.__derive__/3
    lib/cldr/language_tag.ex:159: (module)
```

First I saw the `Jaon` typo, but the actual error is that it needs to be true/false return and not a tuple return.